### ISSUE TITLE
simple_blockchain

### ISSUE THREAD

**Issue by Partygrib** [SemenMartynov/Software-Engineering-2022#310]
Student, group: Khmarenko Gleb, 3530901/90202
URL: https://github.com/Partygrib/simple_blockchain
Any comments: TBD, Python, Flask

**Comment by SemenMartynov** [comment]
У тебя есть имена (ИПы) хостов, так что не обязательно ещё и портам разносить.
```
version: "3.8"

services:
  service_1:
    image: simple-chain
    container_name: service_1
    environment:
      NONCE_MODE: 0
      PORT: 8081
      NEIGHBORS: service_2:8081,service_3:8081
      PYTHONUNBUFFERED: 1

  service_2:
    image: simple-chain
    container_name: service_2
    environment:
      NONCE_MODE: 1
      PORT: 8081
      NEIGHBORS: service_1:8081,service_3:8081
      PYTHONUNBUFFERED: 1
    depends_on:
      - service_1

  service_3:
    image: simple-chain
    container_name: service_3
    environment:
      NONCE_MODE: 2
      PORT: 8081
      NEIGHBORS: service_1:8081,service_2:8081
      MASTER: true
      PYTHONUNBUFFERED: 1
    depends_on:
      - service_1
      - service_2
```
И появляется порт по умолчанию, значит и парсить легче... И можно избавиться от жудкого хардкода `neighbors = ["127.0.0.1:8081", "127.0.0.1:8082"]`...
